name: Preview Deploy

on:
  pull_request:
    branches: [ master, main ]   # triggers on PRs into master or main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python toolchain for your generator
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Your site build depends on pandoc
      - run: sudo apt-get update && sudo apt-get install -y pandoc

      # Install deps and build the static site into ./docs
      - run: pip install -r requirements.txt
      - run: python run.py

      # Upload the generated site as the Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
