name: Preview Deploy

on:
  pull_request:
    branches: [ master, main ]
    paths:
      - 'run.py'
      - 'run-utf8.py'
      - 'requirements.txt'
      - 'problems/**'
      - 'pages/**'
      - 'utils/**'
      - 'templates/**'
      - '.github/workflows/pages-preview.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python with pip cache (speeds up installs a lot)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      # Pandoc is required by your generator
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Build site
        run: python run.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    name: Deploy preview
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: preview           # Make sure Settings → Environments → preview allows all branches
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
